name       : perl-bit-vector
version    : 7.4
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/S/ST/STBEY/Bit-Vector-7.4.tar.gz : 3c6daa671fecfbc35f92a9385b563d65f50dfc6bdc8b4805f9ef46c0d035a926
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Bit::Vector - Efficient bit vector, set of integers and "big int" math
    library
description: |
    Efficient bit vector, set of integers and "big int" math library
builddeps  :
    - perl-carp-clan
rundeps    :
    - perl-carp-clan
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
